#!/usr/bin/env bash
# VibeGates gate G5/R-13 — GIST detector, v5 (ADR-0004 sanctioned set).
# ── CONTRACT (G0; acceptance set = enforcement/tests/run-fixtures.sh —
#    a finding outside this contract is a contract-change proposal, R-23) ──
# COVERED: regular blobs (100644/100755); staged mode = full staged content of
#   touched files (touching adopts content; deletions excluded), --tree = all
#   tracked files; invocation auto-normalizes to the repo root; content
#   scanned as bytes after NUL-stripping (UTF-16 matchable, optional BOM
#   tolerated); comment context = line-leading markers #(non-shebang), //,
#   //!, /*, /*!, *, <!--, ;, -- OR a trailing #, //, /* after code;
#   English + French uncertainty markers incl. accented forms and the U+2019
#   apostrophe, locale-pinned.
# OUT OF SCOPE, declared: symlinks/gitlinks skipped WITH NOTICE; Markdown,
#   docs/passes/ and enforcement/ excluded in BOTH modes (a leading * is
#   indistinguishable from block-comment continuation; prose belongs to
#   R-13/G2); SQL/asm trailing comments (-- and ;) in trailing position;
#   admissions without an AI reference on the same line or split across
#   lines — the G2 attestation is the human backstop; Python docstrings
#   ("""/'''), %-comments (LaTeX/Erlang), REM (batch) and the VB apostrophe
#   are declared residual blind spots (ADR-0004): the admission marker sits
#   on a different line from the docstring opener, out of this guard's
#   single-line contract.
# OUTPUT REDACTED like gate-secrets (path:line only — the two guards share a
#   CI stream, and a credential can share a line with a GIST comment).
# FAIL-CLOSED on every error path. Version history: v1–v4 rejected in G2
#   review (round 4 → escalation ADR-0004) — see docs/passes/pass-4-report.md U2.
# Basis: GIST = AI-reference + uncertainty marker in one comment — admitted
#   non-comprehension of merged code [TechDebt 2026, DOI
#   10.1145/3794915.3795777, abs]. It never integrates naked (R-13/P3).
# Usage: gate-gist.sh [--tree]     Exit 2 = block.

set -u
if locale -a 2>/dev/null | grep -qiE '^C\.utf-?8$'; then export LC_ALL=C.UTF-8; else export LC_ALL=C; fi
MODE="${1:-}"
fail_closed() { echo "BLOCKED (VibeGates G5/R-13): GIST scan could not run — $1. Failing closed." >&2; exit 2; }
git rev-parse --is-inside-work-tree >/dev/null 2>&1 || fail_closed "not inside a work tree"
TOP="$(git rev-parse --show-toplevel 2>/dev/null)" && [ -n "$TOP" ] || fail_closed "cannot resolve repo root"
cd "$TOP" || fail_closed "cannot cd to repo root"

A_GRAVE=$'(\xc3\xa0|\xc3\x80)'
U_CIRC=$'\xc3\xbb'
E_ACUTE=$'\xc3\xa9'
APOS=$'(\x27|\xe2\x80\x99)'
BOM=$'(\xef\xbb\xbf|\xff\xfe|\xfe\xff)?'
AI_REF='([Cc]opilot|[Cc]laude|[Gg]emini|[Cc]hat[Gg][Pp][Tt]|[Cc]ursor|[Dd]evin|AI[- ]generated|generated by AI|l'"$APOS"'IA|par (l'"$APOS"')?IA)'
UNCERT='([Nn]ot sure|[Nn]o idea|[Dd]on'"$APOS"'t (fully )?underst|[Nn]ot fully underst|[Nn]eed(s)? (to )?test|[Uu]ntested|[Tt]emporary|[Hh]ope (this|it) works|[Ss]eems to work|[Mm]ight break|[Pp]as s(u|'"$U_CIRC"')r|('"$A_GRAVE"'|[Aa]) v('"$E_ACUTE"'|e)rifier|[Pp]as compris)'
# Shebang guard on # only; //! and /*! covered (Rust inner docs, Doxygen).
LEAD='^'"$BOM"'[[:space:]]*(#([^!]|$)|//|/\*|\*|<!--|;|--)'
TRAIL='[^[:space:]].*[[:space:]](#|//|/\*)'

TMP="$(mktemp)" && [ -n "$TMP" ] && [ -w "$TMP" ] || fail_closed "mktemp failed"
trap 'rm -f "$TMP"' EXIT

EXCL=(':(exclude)enforcement/gate-*' ':(exclude)enforcement/lint-*' ':(exclude)enforcement/tests/' ':(exclude)docs/passes/' ':(exclude)*.md')
echo "NOTICE (GIST): excluded per contract — guard files, enforcement/tests/, docs/passes/, *.md (ADR-0004 parity; the rest of the tree IS scanned)." >&2
if [ "$MODE" = "--tree" ]; then
  git ls-files -z -- . "${EXCL[@]}" >"$TMP" 2>/dev/null || fail_closed "git file-list error"
else
  git diff --cached --name-only -z --diff-filter=d -- . "${EXCL[@]}" >"$TMP" 2>/dev/null || fail_closed "git file-list error"
fi

FOUND=0
while IFS= read -r -d '' f; do
  m="$(git ls-files -s -- "$f" 2>/dev/null | awk '{print $1; exit}')"
  case "$m" in
    120000|160000) echo "NOTICE (GIST): skipped non-blob '$f' (mode $m — out of contract scope)." >&2; continue ;;
  esac
  git show ":$f" >/dev/null 2>&1 || fail_closed "git show failed for '$f'"
  LNS="$(git show ":$f" 2>/dev/null | tr -d '\000' | grep -anE "($LEAD|$TRAIL)" | grep -aE "$AI_REF" | grep -aE "$UNCERT" | cut -d: -f1 | sort -un || true)"
  if [ -n "$LNS" ]; then
    [ "$FOUND" -eq 0 ] && echo "BLOCKED (VibeGates G5/R-13 — GIST): AI-referencing comment admitting uncertainty about merged code (locations only — inspect locally). Understand it (P3), or contract it in the debt register with owner + due date:" >&2
    FOUND=1
    N=$(printf '%s\n' "$LNS" | wc -l)
    printf '%s\n' "$LNS" | head -5 | while IFS= read -r ln; do
      printf '%s:%s: [GIST admission — inspect locally]\n' "$f" "$ln" >&2
    done
    [ "$N" -gt 5 ] && printf '%s: (+%d more lines not listed)\n' "$f" "$((N-5))" >&2
  fi
done <"$TMP"

[ "$FOUND" -ne 0 ] && exit 2
echo "OK (GIST): no AI-uncertainty admissions in scope."
exit 0
